name: Build and Release Tauri App

on:
  push:
    tags:
      - 'v*'

env:
  PROJECT_NAME: studiffy-cours
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build and Bundle (${{ matrix.os }})
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        os: [linux, windows, macos]
        include:
          - os: linux
            runner: ubuntu-22.04
            target: x86_64-unknown-linux-gnu
          - os: windows
            runner: windows-latest
            target: x86_64-pc-windows-msvc
          - os: macos
            runner: macos-latest
            target: aarch64-apple-darwin

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Cache Rust dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            src-tauri/target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Cache Bun dependencies
        uses: actions/cache@v3
        with:
          path: |
            node_modules
            ~/.bun
          key: ${{ runner.os }}-bun-${{ hashFiles('**/package.json') }}

      - name: Install Bun
        shell: bash
        run: |
          curl -fsSL https://bun.sh/install | bash
          echo "$HOME/.bun/bin" >> $GITHUB_PATH
        if: matrix.os != 'windows'

      - name: Install Bun (Windows)
        shell: pwsh
        run: |
          irm bun.sh/install.ps1 | iex
          Add-Content $env:GITHUB_PATH "$env:USERPROFILE\.bun\bin"
        if: matrix.os == 'windows'

      - name: Install system dependencies (Linux only)
        if: matrix.os == 'linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev libglib2.0-dev patchelf

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}
          profile: minimal

      - name: Install frontend dependencies
        run: bun install

      - name: Inject .env
        shell: bash
        run: echo "VITE_API_BASE_URL=${{ secrets.VITE_API_BASE_URL }}" >> .env

      - name: Build Tauri app
        env:
          PKG_CONFIG_PATH: /usr/lib/x86_64-linux-gnu/pkgconfig
          TAURI_SIGNING_PRIVATE_KEY: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY }}
          TAURI_SIGNING_PRIVATE_KEY_PASSWORD: ${{ secrets.TAURI_SIGNING_PASSWORD }}
        run: bunx tauri build --verbose

      - name: Generate latest.json and package artifacts
        shell: bash
        run: |
          version="${{ github.ref_name }}"
          version="${version#v}"
          pub_date="$(date -u +'%Y-%m-%dT%H:%M:%SZ')"

          mkdir -p output
          case "${{ matrix.os }}" in
          linux)
            sig="src-tauri/target/release/bundle/appimage/${{ env.PROJECT_NAME }}_${version}_amd64.AppImage.sig"
            app="src-tauri/target/release/bundle/appimage/${{ env.PROJECT_NAME }}_${version}_amd64.AppImage"
            cp "$app" output/
            cp "$sig" output/
            ;;
          macos)
            app="src-tauri/target/release/bundle/macos/${{ env.PROJECT_NAME }}.app"
            tarball="output/${{ env.PROJECT_NAME }}_${version}_aarch64.app.tar.gz"
            tar -czf "$tarball" -C "$(dirname "$app")" "$(basename "$app")"
            ;;
          windows)
            sig="src-tauri/target/release/bundle/msi/${{ env.PROJECT_NAME }}_${version}_x64_en-US.msi.sig"
            app="src-tauri/target/release/bundle/msi/${{ env.PROJECT_NAME }}_${version}_x64_en-US.msi"
            cp "$app" output/
            cp "$sig" output/
            ;;
          esac

    # Upload the platform-specific artifacts
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: bundle-${{ matrix.os }}
          path: output
          retention-days: 1

  release:
    name: Release to studiffy-release
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: bundle-linux
          path: ./artifacts/linux
      - uses: actions/download-artifact@v4
        with:
          name: bundle-macos
          path: ./artifacts/macos
      - uses: actions/download-artifact@v4
        with:
          name: bundle-windows
          path: ./artifacts/windows

      - run: |
          version="${{ github.ref_name }}"
          version="${version#v}"
          pub_date="$(date -u +'%Y-%m-%dT%H:%M:%SZ')"

          # Generate the combined latest.json
          cat <<EOF > latest.json
          {
            "version": "$version",
            "notes": "Release $version",
            "pub_date": "$pub_date",
            "platforms": {
              "linux-x86_64": {
                "signature": "$(cat artifacts/linux/${{ env.PROJECT_NAME }}_${version}_amd64.AppImage.sig | sed 's/"/\\"/g' | tr -d '\n')",
                "url": "https://raw.githubusercontent.com/med-aziz-guennichi/studiffy-release/main/releases/v${version}/appimage/${{ env.PROJECT_NAME }}_${version}_amd64.AppImage"
              },
              "darwin-aarch64": {
                "signature": "",
                "url": "https://raw.githubusercontent.com/med-aziz-guennichi/studiffy-release/main/releases/v${version}/macos/${{ env.PROJECT_NAME }}_${version}_aarch64.app.tar.gz"
              },
              "windows-x86_64": {
                "signature": "$(cat artifacts/windows/${{ env.PROJECT_NAME }}_${version}_x64_en-US.msi.sig | sed 's/"/\\"/g' | tr -d '\n')",
                "url": "https://raw.githubusercontent.com/med-aziz-guennichi/studiffy-release/main/releases/v${version}/msi/${{ env.PROJECT_NAME }}_${version}_x64_en-US.msi"
              }
            }
          }
          EOF

      - run: |
          git clone https://x-access-token:${{ secrets.RELEASE_PAT }}@github.com/med-aziz-guennichi/studiffy-release.git release-repo
          
          # Create directories and copy files
          mkdir -p release-repo/releases/${{ github.ref_name }}/appimage
          mkdir -p release-repo/releases/${{ github.ref_name }}/macos
          mkdir -p release-repo/releases/${{ github.ref_name }}/msi
          
          # Copy platform-specific files
          cp artifacts/linux/* release-repo/releases/${{ github.ref_name }}/appimage/
          cp artifacts/macos/* release-repo/releases/${{ github.ref_name }}/macos/
          cp artifacts/windows/* release-repo/releases/${{ github.ref_name }}/msi/
          
          # Copy the combined latest.json
          cp latest.json release-repo/latest.json

      - run: |
          cd release-repo
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git fetch origin main
          git rebase origin/main
          git add .
          git commit -m "Release ${{ github.ref_name }} (all platforms)"
          git push --force-with-lease
