name: Build and Release Tauri App (Windows only)

on:
  push:
    tags:
      - 'v*' # Runs on tag pushes like v1.0.0

jobs:
  build:
    name: Build Windows
    runs-on: windows-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          rust-version: stable
          toolchain: stable
          override: true
      
      - name: Install Bun
        shell: pwsh
        run: |
          curl -fsSL https://bun.sh/install | bash
          Write-Host "Adding Bun to PATH for Windows"
          [System.IO.File]::WriteAllText("$env:SystemDrive\temp\path.txt", "$HOME\.bun\bin")
          Write-Host "Ensure the above is appended for PATH"

      - name: Install dependencies
        run: bun install

      - name: Install Tauri CLI
        run: cargo install tauri-cli

      - name: Build Tauri App
        run: cargo tauri build
          
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: bundle-windows
          path: |
            src-tauri/target/release/bundle
            src-tauri/target/release/bundle/latest.json

  release:
    name: Push to studiffy-release
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          path: ./artifacts

      - name: Clone studiffy-release repo
        run: |
          git clone https://x-access-token:${{ secrets.RELEASE_PAT }}@github.com/med-aziz-guennichi/studiffy-release.git release-repo

      - name: Copy artifacts to release repo
        run: |
          mkdir -p release-repo/releases/${{ github.ref_name }}
          cp -r artifacts/*/ ./release-repo/releases/${{ github.ref_name }}/
          cp artifacts/*/latest.json ./release-repo/latest.json

      - name: Commit and push to public repo
        run: |
          cd release-repo
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add .
          git commit -m "Release ${{ github.ref_name }} for Windows"
          git push
