name: Build and Release Tauri App

on:
  push:
    tags:
      - 'v*'

env:
  PROJECT_NAME: studiffy-cours
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build and Bundle (${{ matrix.target }})
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        include:
          - os: linux
            runner: ubuntu-22.04
            target: x86_64-unknown-linux-gnu
            artifact_name: linux
          - os: windows
            runner: windows-latest
            target: x86_64-pc-windows-msvc
            artifact_name: windows
          - os: macos
            runner: macos-12
            target: x86_64-apple-darwin
            artifact_name: macos-x86_64
          - os: macos
            runner: macos-12
            target: aarch64-apple-darwin
            artifact_name: macos-aarch64
            # For Apple Silicon builds, we need to set some additional env vars
            env:
              MACOSX_DEPLOYMENT_TARGET: "11.0"
              SDKROOT: /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Cache Rust dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            src-tauri/target
          key: ${{ runner.os }}-${{ matrix.target }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Cache Bun dependencies
        uses: actions/cache@v3
        with:
          path: |
            node_modules
            ~/.bun
          key: ${{ runner.os }}-bun-${{ hashFiles('**/package.json') }}

      - name: Install Bun
        shell: bash
        run: |
          curl -fsSL https://bun.sh/install | bash
          echo "$HOME/.bun/bin" >> $GITHUB_PATH
        if: matrix.os != 'windows'

      - name: Install Bun (Windows)
        shell: pwsh
        run: |
          irm bun.sh/install.ps1 | iex
          Add-Content $env:GITHUB_PATH "$env:USERPROFILE\.bun\bin"
        if: matrix.os == 'windows'

      - name: Install system dependencies (Linux only)
        if: matrix.os == 'linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev libglib2.0-dev patchelf

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}
          profile: minimal

      # For macOS ARM builds, we need to ensure we're using the correct architecture
      - name: Setup macOS ARM build environment
        if: matrix.target == 'aarch64-apple-darwin'
        run: |
          echo "Setting up ARM build environment"
          # Ensure we're building for ARM64
          export ARCHFLAGS="-arch arm64"
          # Make sure we're using the correct SDK
          sudo xcode-select -s /Applications/Xcode.app/Contents/Developer
          echo "ARCHFLAGS=-arch arm64" >> $GITHUB_ENV
          echo "RUSTFLAGS=-C link-arg=-arch -C link-arg=arm64" >> $GITHUB_ENV

      - name: Install frontend dependencies
        run: bun install

      - name: Inject .env
        shell: bash
        run: echo "VITE_API_BASE_URL=${{ secrets.VITE_API_BASE_URL }}" >> .env

      - name: Build Tauri app
        env:
          PKG_CONFIG_PATH: /usr/lib/x86_64-linux-gnu/pkgconfig
          TAURI_SIGNING_PRIVATE_KEY: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY }}
          TAURI_SIGNING_PRIVATE_KEY_PASSWORD: ${{ secrets.TAURI_SIGNING_PASSWORD }}
        run: |
          if [ "${{ matrix.target }}" == "aarch64-apple-darwin" ]; then
            # Explicitly set the architecture for Apple Silicon builds
            echo "Building for Apple Silicon"
            export CC="clang -target arm64-apple-macos11"
            export CXX="clang++ -target arm64-apple-macos11"
          fi
          bunx tauri build --target ${{ matrix.target }} --verbose

      - name: Generate latest.json and package artifacts
        shell: bash
        run: |
          version="${{ github.ref_name }}"
          version="${version#v}"
          pub_date="$(date -u +'%Y-%m-%dT%H:%M:%SZ')"

          mkdir -p output
          case "${{ matrix.os }}" in
          linux)
            sig="src-tauri/target/${{ matrix.target }}/release/bundle/deb/${{ env.PROJECT_NAME }}_${version}_amd64.deb.sig"
            app="src-tauri/target/${{ matrix.target }}/release/bundle/deb/${{ env.PROJECT_NAME }}_${version}_amd64.deb"
            cp "$app" output/
            cp "$sig" output/
            ;;
          macos)
            app="src-tauri/target/${{ matrix.target }}/release/bundle/macos/${{ env.PROJECT_NAME }}.app"
            sig="src-tauri/target/${{ matrix.target }}/release/bundle/macos/${{ env.PROJECT_NAME }}.app.tar.gz.sig"
            if [ "${{ matrix.target }}" == "aarch64-apple-darwin" ]; then
              tarball="output/${{ env.PROJECT_NAME }}_${version}_aarch64.app.tar.gz"
            else
              tarball="output/${{ env.PROJECT_NAME }}_${version}_x86_64.app.tar.gz"
            fi
            tar -czf "$tarball" -C "$(dirname "$app")" "$(basename "$app")"
            cp "$sig" output/
            ;;
          windows)
            sig="src-tauri/target/${{ matrix.target }}/release/bundle/msi/${{ env.PROJECT_NAME }}_${version}_x64_en-US.msi.sig"
            app="src-tauri/target/${{ matrix.target }}/release/bundle/msi/${{ env.PROJECT_NAME }}_${version}_x64_en-US.msi"
            cp "$app" output/
            cp "$sig" output/
            ;;
          esac

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: bundle-${{ matrix.artifact_name }}
          path: output
          retention-days: 1

  release:
    name: Release to studiffy-release
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: bundle-linux
          path: ./artifacts/linux
      - uses: actions/download-artifact@v4
        with:
          name: bundle-macos-x86_64
          path: ./artifacts/macos-x86_64
      - uses: actions/download-artifact@v4
        with:
          name: bundle-macos-aarch64
          path: ./artifacts/macos-aarch64
      - uses: actions/download-artifact@v4
        with:
          name: bundle-windows
          path: ./artifacts/windows

      - run: |
          version="${{ github.ref_name }}"
          version="${version#v}"
          pub_date="$(date -u +'%Y-%m-%dT%H:%M:%SZ')"

          # Generate the combined latest.json
          cat <<EOF > latest.json
          {
            "version": "$version",
            "notes": "Release $version",
            "pub_date": "$pub_date",
            "platforms": {
              "linux-x86_64": {
                "signature": "$(cat artifacts/linux/${{ env.PROJECT_NAME }}_${version}_amd64.deb.sig | sed 's/"/\\"/g' | tr -d '\n')",
                "url": "https://raw.githubusercontent.com/med-aziz-guennichi/studiffy-release/main/releases/v${version}/deb/${{ env.PROJECT_NAME }}_${version}_amd64.deb"
              },
              "darwin-x86_64": {
                "signature": "$(cat artifacts/macos-x86_64/${{ env.PROJECT_NAME }}_${version}_x86_64.app.tar.gz.sig | base64 -w 0 | sed 's/"/\\"/g')",
                "url": "https://raw.githubusercontent.com/med-aziz-guennichi/studiffy-release/main/releases/v${version}/macos/${{ env.PROJECT_NAME }}_${version}_x86_64.app.tar.gz"
              },
              "darwin-aarch64": {
                "signature": "$(cat artifacts/macos-aarch64/${{ env.PROJECT_NAME }}_${version}_aarch64.app.tar.gz.sig | base64 -w 0 | sed 's/"/\\"/g')",
                "url": "https://raw.githubusercontent.com/med-aziz-guennichi/studiffy-release/main/releases/v${version}/macos/${{ env.PROJECT_NAME }}_${version}_aarch64.app.tar.gz"
              },
              "windows-x86_64": {
                "signature": "$(cat artifacts/windows/${{ env.PROJECT_NAME }}_${version}_x64_en-US.msi.sig | sed 's/"/\\"/g' | tr -d '\n')",
                "url": "https://raw.githubusercontent.com/med-aziz-guennichi/studiffy-release/main/releases/v${version}/msi/${{ env.PROJECT_NAME }}_${version}_x64_en-US.msi"
              }
            }
          }
          EOF

      - name: Clone and prepare release repo
        run: |
          git clone https://x-access-token:${{ secrets.RELEASE_PAT }}@github.com/med-aziz-guennichi/studiffy-release.git release-repo
          cd release-repo
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          
          # Reset any changes and pull latest
          git reset --hard
          git clean -fd
          git pull origin main

      - name: Copy release files
        run: |
          # Create directories and copy files
          mkdir -p release-repo/releases/${{ github.ref_name }}/deb
          mkdir -p release-repo/releases/${{ github.ref_name }}/macos
          mkdir -p release-repo/releases/${{ github.ref_name }}/msi
          
          # Copy platform-specific files
          cp artifacts/linux/* release-repo/releases/${{ github.ref_name }}/deb/ || echo "No Linux files to copy"
          cp artifacts/macos-x86_64/* release-repo/releases/${{ github.ref_name }}/macos/ || echo "No macOS x86_64 files to copy"
          cp artifacts/macos-aarch64/* release-repo/releases/${{ github.ref_name }}/macos/ || echo "No macOS aarch64 files to copy"
          cp artifacts/windows/* release-repo/releases/${{ github.ref_name }}/msi/ || echo "No Windows files to copy"
          
          # Copy the combined latest.json
          cp latest.json release-repo/latest.json

      - name: Commit and push changes
        run: |
          cd release-repo
          git add .
          if git diff-index --quiet HEAD --; then
            echo "No changes to commit"
          else
            git commit -m "Release ${{ github.ref_name }} (all platforms)"
            git push origin main
          fi