name: Frontend Lint Check

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # needed to get full history for BASE_SHA

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Run ESLint
        run: bun run lint

      - name: Run Prettier
        run: bun run format:write

      - name: Set BASE_SHA
        id: set-base-sha
        run: |
          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
            echo "BASE_SHA=${{ github.event.pull_request.base.sha }}" >> $GITHUB_ENV
          else
            echo "BASE_SHA=${{ github.event.before }}" >> $GITHUB_ENV
          fi

      - name: Code Review GPT
        uses: mattzcarey/code-review-gpt@v0.8.0
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BASE_SHA: ${{ env.BASE_SHA }}
