name: Frontend Lint Check

on:
  pull_request:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Run ESLint
        run: bun run lint

      - name: Run Prettier
        run: bun run format:write

      - name: Send Code to Hugging Face for Review
        run: |
          curl -X POST https://api-inference.huggingface.co/models/bigcode/starcoderbase-1b \
            -H "Authorization: Bearer ${{ secrets.HUGGINGFACE_API_KEY }}" \
            -d '{"inputs": "Please review the following code: <your_code_here>"}' \
            -o result.json

      - name: Display Hugging Face Review Result
        run: cat result.json

      - name: Comment on PR with Review
        run: |
          REVIEW=$(cat result.json | jq -r '.choices[0].text')
          curl -X POST \
            -H "Authorization: token ${{ github.token }}" \
            -d '{"body": "Code Review: \n\n'"$REVIEW"'"}' \
            https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/comments

      